spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/ntspbms615db
    type: org.apache.commons.dbcp2.BasicDataSource
    password: root